import { Dictionary } from '@/types/dictionary'

const en: Dictionary = {
  header: {
    signInButton: 'Login',
    navOptions: {
      features: 'Features',
      howItWorks: 'How It Works',
      faq: 'FAQ',
    },
    callToActionOne: 'Get Started',
    callToActionTwo: 'Connect GitHub',
  },

  loginPage: {
    title: 'Login',
    description: 'Access your account through GitHub',
    buttonTitle: 'Login with GitHub',
  },

  landingPage: {
    hero: {
      welcomeTo: 'Welcome to',
      description:
        'Automatically generate professional README.md files for your GitHub repositories',
      callToActionOne: 'Get Started',
      callToActionTwo: 'Connect GitHub',
      sloganOne: 'Ready in seconds',
      SloganTwo: '100% GitHub compatible',

      macWindow: {
        fileTitle: 'README.md - ReadmeGen',
        projectName: 'Amazing Project',
        projectDescription:
          'An incredible description of your project automatically generated by ReadmeGen.',
        installation: 'Installation',
        installationDescription: 'npm install amazing-project',
        use: 'Usage',
        useDescription: 'Detailed instructions on how to use',
      },
    },

    whySection: {
      preTitle: 'Why ReadmeGen?',
      title: 'Create impressive READMEs in minutes',
      description:
        'Our AI-powered tool transforms how you document your projects',

      cards: [
        {
          title: 'Save Time',
          description:
            'Let our tool generate your README files so you can focus on writing code.',
        },
        {
          title: 'Professional Results',
          description:
            'All generated READMEs follow best practices and look great.',
        },
        {
          title: 'Easy to Use',
          description:
            'Just connect your GitHub repository and let the magic happen.',
        },
      ],
      callToAction: 'Try Now',
    },

    howItWorks: {
      preTitle: 'How It Works',
      title: 'Three simple steps to a perfect README',
      callToAction: 'Try Now',
      steps: [
        {
          title: 'Connect Your GitHub',
          description:
            'Authorize ReadmeGen to access your repositories for analysis.',
        },
        {
          title: 'Select Repository',
          description:
            'Choose which project you want to generate a professional README for.',
        },
        {
          title: 'Generate and Customize',
          description:
            'Our AI creates a complete README that you can edit and publish.',
        },
      ],
    },

    testimonialSection: {
      preTitle: 'Testimonials',
      title: 'What our users say',
      description:
        'Developers from around the world are saving time and improving their projects with ReadmeGen.',

      testimonials: [
        {
          testimonial:
            '"ReadmeGen completely transformed my workflow. I now have professional READMEs in all my projects with no extra effort."',
          user: 'Maria Silva, Full Stack Developer',
        },
        {
          testimonial:
            '"My open source projects now have quality documentation, which has significantly increased community contributions."',
          user: 'John Doe, OSS Maintainer',
        },
      ],
    },

    faqSection: {
      preTitle: 'FAQ',
      title: 'Frequently Asked Questions',

      questions: [
        {
          question: 'Is ReadmeGen free?',
          answer:
            'Yes, we offer a free plan that allows you to generate READMEs for public repositories. We also have premium plans with additional features.',
        },
        {
          question: 'Can I customize the generated READMEs?',
          answer:
            'Absolutely! After generation, you can edit any part of the README before publishing it to your repository.',
        },
        {
          question: 'Does ReadmeGen have access to my code?',
          answer:
            'We only analyze repository metadata and file structure to generate the README. We do not store your source code.',
        },
      ],
    },

    callToActionSection: {
      title: 'Ready to improve your READMEs?',
      description:
        'Start generating professional READMEs in minutes and make your projects stand out.',
      buttonOne: 'Get Started',
      buttonTwo: 'View on GitHub',
    },
  },

  dashboardPage: {
    header: {
      credits: 'Credits',
      help: 'Help',
      dropdownItems: {
        profile: 'Profile',
        settings: 'Settings',
        logout: 'Logout',
      },
    },

    sidebar: {
      home: 'Home',
      settings: 'Settings',
      helpSupport: 'Help & Support',
    },

    repositoryList: {
      title: 'Your Repositories',
      loading: 'Loading repositories...',
      noRepositories: 'No repositories found',
      selected: 'Selected',
      refreshRepositories: 'Refresh repository list',
    },

    desktopOnly: 'Use on desktop for a better experience',
    title: 'Dashboard',
    yourRepositories: 'Your Repositories',
    selectRepository: 'Select a repository to get started',
    selectRepositoryDescription:
      'Select a repository from the list to generate a personalized README.',

    logout: 'Log out',
    creditLabel: 'Credit',

    repositoryForm: {
      modalBuy: {
        title: 'Buy Credits',
        description:
          'You do not have enough credit to generate READMEs. Would you like to buy more?',
        buttonBuy: 'Buy Credits',
      },
      title: 'Repository Information',
      repositoryDescriptionLabel: 'Describe your repository',
      repositoryDescriptionPlaceholder:
        'Ex. This repository is a web application that allows users to create and share funny memes.',

      repositoryThumbLabel: 'Add a cover image?',
      repositoryThumbUrlLabel: 'Cover image URL',
      repositoryThumbUrlPlaceholder: 'Ex. https://example.com/image.jpg',
      submitButton: 'Generate README',
      submittingButton: 'Generating README...',

      saveOnGithub: 'Save on GitHub',

      repoInfo: {
        name: 'Repository Name:',
        description: 'Repository Description:',
        languages: 'Languages',
      },
    },

    markdownEditor: {
      buttonCode: 'Code',
      buttonPreview: 'Preview',
      downloadButton: 'Download README',
      copyButton: 'Copy Markdown',
      downloadSuccess: 'README downloaded successfully!',
      copySuccess: 'Markdown copied successfully!',
    },

    messageErrors: {
      excerptRequired: 'Repository description is required',
      thumbRequired: 'Cover image URL is required',
      generic: 'Something went wrong. Please try again.',
      errorCodeOne: 'We are working on it, please try again later.',
      noCredit: 'You do not have enough credit to generate READMEs',
      userNotFound: 'User not found',
    },
  },

  footer: {
    copyright: 'All rights reserved.',
    linkLabels: {
      terms: 'Terms',
      privacy: 'Privacy',
      contact: 'Contact',
    },
  },
}

export default en
